# Generated by Django 2.1 on 2018-09-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0002_auto_20180904_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
