# Generated by Django 2.1.1 on 2018-09-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vroom', '0003_auto_20180904_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
